application: flomosa
version: 1
runtime: python
api_version: 1

inbound_services:
- mail
- xmpp_message

handlers:
- url: /
  script: app_main.py
  #login: admin

- url: /test
  script: dot_test.py

- url: /requests/.*
  script: app_request.py
  #secure: always
  #login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /_ah/queue/request-store
  script: queue_request_store.py
  #login: admin

- url: /_ah/queue/request-process
  script: queue_request_process.py
  #login: admin

- url: /_ah/queue/mail-viewed
  script: queue_mail_viewed.py
  #login: admin

- url: /_ah/queue/mail-notify
  script: queue_mail_notify.py
  #login: admin

- url: /_ah/mail/.+
  script: mail_handler.py