application: flomosa
version: 2
runtime: python
api_version: 1

inbound_services:
- xmpp_message
- mail

builtins:
- appstats: on
- datastore_admin: on

includes:
- flomosa/api
- flomosa/mail
- flomosa/queue
- flomosa/web

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?flomosa\.kpf$
- ^(.*/)?setup.*
- ^(.*/)?run_tests.*
- ^(.*/)?unittests\.xml$
- ^(.*/)?coverage\.xml$
- ^(.*/)?tools/.*
- ^(.*/)?flomosa/tests/.*