application: flomosa
version: 1
runtime: python
api_version: 1

inbound_services:
- mail
- xmpp_message

handlers:
- url: /
  script: app_main.py
  #login: admin

- url: /viewed/.*
  script: app_viewed.py
  #secure: always

- url: /requests/.*
  script: app_request.py
  #secure: always

- url: /processes/.*
  script: app_process.py
  #secure: always

- url: /teams/.*
  script: app_team.py
  #secure: always

- url: /_ah/queue/process-store
  script: queue_process_store.py
  #login: admin

- url: /_ah/queue/request-store
  script: queue_request_store.py
  #login: admin

- url: /_ah/queue/request-process
  script: queue_request_process.py
  #login: admin

- url: /_ah/queue/mail-viewed
  script: queue_mail_viewed.py
  #login: admin

- url: /_ah/mail/.+
  script: mail_handler.py
  #login: admin