application: flomosa
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /
  script: app_main.py
  #login: admin

- url: /viewed/.*
  script: app_viewed.py

- url: /requests/.*
  script: app_request.py
  #secure: always

- url: /processes/.*
  script: app_process.py
  #secure: always

- url: /teams/.*
  script: app_team.py
  #secure: always

- url: /stats/.*
  script: app_stat.py
  #secure: always
  
- url: /search/.*
  script: app_search.py
  #secure: always

- url: /_ah/queue/request-process
  script: queue_request_process.py
  #login: admin

- url: /_ah/queue/mail-request-notify
  script: queue_mail_request_notify.py
  #login: admin

- url: /_ah/queue/mail-request-confirmation
  script: queue_mail_request_confirmation.py
  #login: admin

- url: /_ah/queue/mail-request-complete
  script: queue_mail_request_complete.py
  #login: admin

- url: /_ah/mail/.+
  script: mail_handler.py
  #login: admin