application: flomosa
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

derived_file_type:
- python_precompiled

handlers:
- url: /
  script: app_index.py
  secure: optional

- url: /account/.*
  script: app_account.py
  secure: always

- url: /viewed/.*
  script: app_viewed.py
  secure: optional

- url: /requests/.*
  script: app_request.py
  secure: optional

- url: /processes/.*
  script: app_process.py
  secure: optional

- url: /executions/.*
  script: app_execution.py
  secure: optional

- url: /steps/.*
  script: app_step.py
  secure: optional

- url: /teams/.*
  script: app_team.py
  secure: optional

- url: /stats/.*
  script: app_stat.py
  secure: optional
  
- url: /search/.*
  script: app_search.py
  secure: optional

- url: /tests/.*
  script: app_test.py
  secure: optional

- url: /_ah/queue/execution-creation
  script: queue_execution_creation.py
  #login: admin

- url: /_ah/queue/execution-process
  script: queue_execution_process.py
  #login: admin

- url: /_ah/queue/step-callback
  script: queue_step_callback.py
  #login: admin

- url: /_ah/queue/request-callback
  script: queue_request_callback.py
  #login: admin

- url: /_ah/queue/request-statistics
  script: queue_request_statistics.py
  #login: admin

- url: /_ah/queue/mail-request-notify
  script: queue_mail_request_notify.py
  #login: admin

- url: /_ah/queue/mail-request-confirmation
  script: queue_mail_request_confirmation.py
  #login: admin

- url: /_ah/queue/mail-request-complete
  script: queue_mail_request_complete.py
  #login: admin

- url: /_ah/queue/mail-request-step
  script: queue_mail_request_step.py
  #login: admin

- url: /_ah/queue/mail-request-reminder
  script: queue_mail_request_reminder.py
  #login: admin

- url: /_ah/mail/feedback@.*flomosa\.appspotmail\.com
  script: mail_handler_feedback.py
  login: admin

- url: /_ah/mail/.+
  script: mail_handler.py
  login: admin