application: flomosa
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /
  script: app_index.py
  secure: optional

- url: /account/.*
  script: app_account.py
  secure: always

- url: /viewed/.*
  script: app_viewed.py
  secure: optional

- url: /requests/.*
  script: app_request.py
  secure: always

- url: /processes/.*
  script: app_process.py
  secure: optional

- url: /teams/.*
  script: app_team.py
  secure: optional

- url: /stats/.*
  script: app_stat.py
  secure: optional
  
- url: /search/.*
  script: app_search.py
  secure: optional

- url: /test-client
  script: app_test_client.py
  secure: never

- url: /_ah/queue/request-process
  script: queue_request_process.py

- url: /_ah/queue/mail-request-notify
  script: queue_mail_request_notify.py

- url: /_ah/queue/mail-request-confirmation
  script: queue_mail_request_confirmation.py

- url: /_ah/queue/mail-request-complete
  script: queue_mail_request_complete.py

- url: /_ah/queue/mail-request-step
  script: queue_mail_request_step.py

- url: /_ah/queue/mail-request-reminder
  script: queue_mail_request_reminder.py

- url: /_ah/mail/feedback@.*flomosa\.appspotmail\.com
  script: mail_handler_feedback.py
  login: admin

- url: /_ah/mail/.+
  script: mail_handler.py
  login: admin