application: flomosa
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

derived_file_type:
- python_precompiled

handlers:
- url: /
  script: web/index.py
  secure: optional

- url: /account/.*
  script: web/account.py
  secure: always

- url: /viewed/.*
  script: web/viewed.py
  secure: optional

- url: /requests/.*
  script: api/request.py
  secure: optional

- url: /processes/.*
  script: api/process.py
  secure: optional

- url: /executions/.*
  script: api/execution.py
  secure: optional

- url: /steps/.*
  script: api/step.py
  secure: optional

- url: /teams/.*
  script: api/team.py
  secure: optional

- url: /stats/.*
  script: api/stat.py
  secure: optional
  
- url: /search/.*
  script: api/search.py
  secure: optional

- url: /tests/.*
  script: web/test.py
  secure: optional

- url: /_ah/queue/execution-creation
  script: queue/execution_creation.py
  #login: admin

- url: /_ah/queue/execution-process
  script: queue/execution_process.py
  #login: admin

- url: /_ah/queue/step-callback
  script: queue/step_callback.py
  #login: admin

- url: /_ah/queue/request-callback
  script: queue/request_callback.py
  #login: admin

- url: /_ah/queue/request-statistics
  script: queue/request_statistics.py
  #login: admin

- url: /_ah/queue/mail-request-notify
  script: queue/mail/request_notify.py
  #login: admin

- url: /_ah/queue/mail-request-confirmation
  script: queue/mail/request_confirmation.py
  #login: admin

- url: /_ah/queue/mail-request-complete
  script: queue/mail/request_complete.py
  #login: admin

- url: /_ah/queue/mail-request-step
  script: queue/mail/request_step.py
  #login: admin

- url: /_ah/queue/mail-request-reminder
  script: queue/mail/request_reminder.py
  #login: admin

- url: /_ah/mail/feedback@.*flomosa\.appspotmail\.com
  script: mail/feedback_handler.py
  login: admin

- url: /_ah/mail/.+
  script: mail/handler.py
  login: admin